# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


target 'COUM' do
  $RNFirebaseAsStaticFramework = true
  # Comment the next line if you don't want to use dynamic frameworks
  config = use_native_modules!
  use_frameworks!

  # pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
  
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  
 

  # pod 'GoogleSignIn'
  
  # post_install do |installer|
  #   react_native_post_install(installer)
  #   installer.pods_project.targets.each do |target|
  #     target.build_configurations.each do |config|
  #     # some older pods don't support some architectures, anything over iOS 11 resolves that
  #       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
  #     end
  #   end
  # end

end

